# Generated by Django 2.2 on 2020-05-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='面试题目')),
                ('answer', models.TextField(max_length=2000, null=True, verbose_name='面试题答案')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '面试题',
                'verbose_name_plural': '面试题',
                'db_table': 'interview_question',
                'ordering': ['-create_time'],
            },
        ),
    ]
