# Generated by Django 2.2 on 2020-04-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=30, verbose_name='单词')),
                ('chinese_translation', models.CharField(default=None, max_length=100, verbose_name='汉语意思')),
                ('create_time', models.DateField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'db_table': 'English_word',
                'ordering': ['-create_time'],
            },
        ),
    ]
