# Generated by Django 2.2 on 2020-05-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='english_app.ExaminationModel', verbose_name='属于哪次测验'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='english_app.WordModel', verbose_name='是哪个单词'),
        ),
    ]
