# Generated by Django 2.2 on 2020-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='chinese_translation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='汉语意思'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='english',
            field=models.CharField(max_length=30, unique=True, verbose_name='单词'),
        ),
    ]
