# Generated by Django 2.2.7 on 2020-04-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_app', '0002_auto_20200430_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='已逻辑删除'),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='translate_into_chinese_success',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='翻译成中文正确的次数'),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='translate_into_chinese_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='翻译成中文的总次数'),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='translate_into_english_success',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='中译英正确的次数'),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='translate_into_english_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='中译英总次数'),
        ),
    ]
