# Generated by Django 2.2.7 on 2020-04-30 22:53

from django.db import migrations
import english_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('english_app', '0003_auto_20200430_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'managed': english_app.models.WordManager, 'ordering': ['-create_time'], 'verbose_name': '单词', 'verbose_name_plural': '单词'},
        ),
    ]
