# Generated by Django 2.2.7 on 2020-04-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_app', '0004_auto_20200430_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'ordering': ['-create_time'], 'verbose_name': '单词', 'verbose_name_plural': '单词'},
        ),
    ]
